stages:
  - publish

build_cmps:
  stage: publish
  variables:
    importName: 'PaasComponentsTemplate'
    importModule: '@beisen/paas-components-template'
  only: 
    - tags
  script:
    - /bin/bash ~/publish.sh
    - echo $importName $importModule
    - git clone git@gitlab.beisencorp.com:zhongjiahao/shared-componetns-platform.git
    - cd ./shared-componetns-platform
    - npm install jsonfile ejs shelljs object.values --registry=https://registry.npm.taobao.org
    - node ./build/upgrade.js $importName $importModule