
language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - node_modules/.bin/forever start ./tests/mock-server.js --minUptime 1000 --spinSleepTime 10000
  - npm run cover

after_script:
  - node_modules/.bin/forever stop ./tests/mock-server.js
  - cat coverage/lcov.info | coveralls
